#!/usr/bin/env bash
# GuideBard First-Run Setup Script
# Usage: bash scripts/setup.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[setup]${NC} $1"; }
warn()    { echo -e "${YELLOW}[warn]${NC}  $1"; }
error()   { echo -e "${RED}[error]${NC} $1"; exit 1; }

echo ""
echo "  ╔══════════════════════════════════════╗"
echo "  ║         GuideBard Setup              ║"
echo "  ╚══════════════════════════════════════╝"
echo ""

# ── Check prerequisites ───────────────────────────────────────
command -v docker >/dev/null 2>&1 || error "Docker is required. Install from https://docs.docker.com/get-docker/"
command -v docker compose version >/dev/null 2>&1 || \
  command -v docker-compose >/dev/null 2>&1 || \
  error "Docker Compose is required."

# ── Check for existing .env ───────────────────────────────────
if [ -f .env ]; then
  warn ".env already exists. Skipping configuration (delete it to re-run setup)."
  SKIP_CONFIG=true
else
  SKIP_CONFIG=false
fi

if [ "$SKIP_CONFIG" = false ]; then
  info "Generating .env configuration..."

  # Generate secure random keys
  SECRET_KEY=$(openssl rand -hex 64 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(64))")
  ENCRYPTION_KEY=$(openssl rand -base64 32 2>/dev/null || python3 -c "import secrets, base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode())")
  DB_PASSWORD=$(openssl rand -hex 24 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(24))")
  MINIO_SECRET_KEY=$(openssl rand -hex 24 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(24))")

  # Admin password
  echo ""
  read -rp "  Set admin password (min 8 chars): " ADMIN_PASSWORD
  while [ ${#ADMIN_PASSWORD} -lt 8 ]; do
    warn "Password too short."
    read -rp "  Set admin password (min 8 chars): " ADMIN_PASSWORD
  done

  read -rp "  Admin username [admin]: " ADMIN_USERNAME
  ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

  read -rp "  Admin email [admin@localhost]: " ADMIN_EMAIL
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@localhost}"

  read -rp "  App URL (for links) [http://localhost]: " APP_URL
  APP_URL="${APP_URL:-http://localhost}"

  # Write .env
  cat > .env <<EOF
# ── Generated by setup.sh ────────────────────────────────────
DEPLOYMENT_MODE=single_tenant

SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql+asyncpg://guidebard:${DB_PASSWORD}@postgres:5432/guidebard
DATABASE_URL_SYNC=postgresql://guidebard:${DB_PASSWORD}@postgres:5432/guidebard

REDIS_URL=redis://redis:6379/0

MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=guidebard-minio
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
MINIO_USE_SSL=false
MINIO_BUCKET_PREFIX=guidebard

APP_NAME=GuideBard
APP_URL=${APP_URL}

ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

NEXT_PUBLIC_API_URL=${APP_URL}/api
NEXT_PUBLIC_WS_URL=$(echo "$APP_URL" | sed 's/^http/ws')/ws
NEXT_PUBLIC_APP_NAME=GuideBard
NEXT_PUBLIC_DEPLOYMENT_MODE=single_tenant

CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1
FFMPEG_THREADS=4
EOF
  info ".env created successfully."
fi

# ── Start services ────────────────────────────────────────────
echo ""
info "Starting GuideBard services (this may take a few minutes on first run)..."
docker compose pull --quiet 2>/dev/null || true
docker compose up -d --build

# ── Wait for health ───────────────────────────────────────────
info "Waiting for services to be healthy..."
MAX_WAIT=120; WAITED=0
until docker compose exec -T backend curl -sf http://localhost:8000/health > /dev/null 2>&1; do
  sleep 3; WAITED=$((WAITED+3))
  if [ $WAITED -ge $MAX_WAIT ]; then
    error "Backend didn't start in time. Check: docker compose logs backend"
  fi
  echo -n "."
done
echo ""

echo ""
echo -e "${GREEN}  ✓ GuideBard is running!${NC}"
echo ""
echo "  Open in browser: ${APP_URL:-http://localhost}"
echo "  Username: ${ADMIN_USERNAME:-admin}"
echo ""
echo "  To stop:  docker compose down"
echo "  To view logs: docker compose logs -f"
echo ""
